config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets
  resources :users
  resources :likes
  get "home", to: "tweets#new"
  get "profile/:id", to: "users#show", as: :profile
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "tweets#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :replied_to, class_name: "Tweet", optional: true

  has_many :likes, dependent: :destroy
  has_many :replies, class_name: "Tweet", foreign_key: :replied_to_id, dependent: :nullify


  def like_count
    likes.count
  end

  validates :body, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :email, presence: true, format: {
    with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i,
    message: "only email format"
  }

  validates :username, presence: true, uniqueness: true

  validates :name, presence: true

  validates :password, length: { minimum: 6 }, allow_blank: true

  enum role: { user: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name avatar password_confirmation])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @like = current_user.likes.build(tweet: @tweet)
    if @like.save
      redirect_back(fallback_location: root_path)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @like = current_user.likes.find_by(tweet: @tweet)
    if @like.destroy
      redirect_back(fallback_location: root_path)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweets = Tweet.all
    @user = User.all
    @tweetnew = Tweet.new
    @likes = Like.all
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @tweets = Tweet.all
    @users = User.all
    @likes = Like.all
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet[:user_id] = current_user.id
    if @tweet.save
      redirect_to request.referer, notice: "Tweet was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: "Tweet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to request.referer, notice: "Tweet was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body, :replied_to_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @tweets = Tweet.all
    @likes = Like.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :username, :name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetable</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header  class="header_box">
      <div>
        <%= link_to home_path do %>
          <div>
            <%= image_tag 'Icon-tweetable.png' %>
          </div>
        <% end %>
      </div>
      <div>
        <input type="checkbox" id="check" />
        <label for="check" class="hamburger-menu" id="close">
          <%= image_tag 'Icon-hamburger-menu.svg' %>
        </label>
        <label for="check" class="hamburger-menu" id="open">
          <%= image_tag 'Icon-close.svg' %>
        </label>
        <div class="nav-links">
          <% if user_signed_in? %>
          <ul class="style-none">
            <li><%= link_to "Profile", user_path(current_user.id)%></li>
            <li><%= button_to "Log Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to log out?" },class: "buttom_logout" %></li>
          </ul>
          <% else %>
          <ul class="style-none">
            <li><span> Login to start the tweeting madness! <span></li>
            <li class="buttom_login"><%= link_to "Login", user_session_path %></li>
          </ul>
          <% end %>
        <div>
      </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer class="footer_box">
      <div>
          <p class="text-center">© 2023 - Codeable Tweetable</p>
          <p class="text-center">Build with ♥ by</p>
          <div>
            <%= link_to "https://www.linkedin.com/in/alex-mendoza-etchebarne/" do %>
              <div class="footer_link">
                <div class="icon_footer">
                  <%= image_tag 'Icon-linkedin.png' %>
                </div>
                <p> Alex Mendoza</p>
              </div>
            <% end %>
          </div>
      </div>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <%if replied_to_id %>
  <%= form.hidden_field :replied_to_id, value: replied_to_id %>
  <% end %>
  <div class="box_father">
    <div class="box_center">
      <%= form.text_area :body, placeholder: "Remember to thing before write...", class: "new_tweet_box" %>
    </div>

    <div class="box_tweet">
      <div>
        <% if tweet[:body].nil? %>
          <%= form.submit :Tweet, class: "button_tweet" %>
        <% else %>
          <%= form.submit :Update, class: "button_tweet" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
    <div>
      <% @user.each do |user| %>
        <div>
          <%= link_to user do %>
            <% if user.id == tweet.user_id%>
              <%if user.avatar.attached?%>
                <div >
                  <%= image_tag user.avatar%>
                </div>
              <%else%>
                <div >
                  <%= image_tag "icons_avatars/unknow_icon.png"%>
                </div>
              <%end%>
              <%= user.name%>
              @<%= user.username%>
            <%end%>
          <% end %>
        </div>
      <% end %>
      <%= link_to tweet do %>
        <div>
          <%= time_ago_in_words(tweet.created_at) %> ago
          <%= tweet.body %>
        </div>
      <% end %>
    </div>
    <p>
      <strong>Replies count:</strong>
      <%= @tweets.where(replied_to_id: tweet.id).size %>
    </p>

    <p>
      <strong>Likes count:</strong>
      <%= tweet.likes_count %>
    </p>
</div>

app/views/tweets/edit.html.erb
<h2 class= "home_text">Edit Tweet</h2>

<%= form_with(model: @tweet) do |form| %>
  <div class="box_father">
    <div class="box_center">
      <%= form.text_area :body, placeholder: "Remember to thing before write...", class: "new_tweet_box" %>
    </div>

    <div class="box_tweet">
      <div>
        <%= form.submit :Update, class: "button_tweet"  %>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>


<div id="tweets">
  <% @tweets.reverse().each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h2 class= "home_text">HOME</h2>

<div>
  <% if user_signed_in?%>
    <%= render "form", tweet: @tweet, replied_to_id: nil %>
  <% end %>
</div>

<div id="tweets">
    <% @tweets.reverse().each do |tweet| %>
    <div class="tweet_box">
      <% @users.each do |user| %>
          <%= link_to profile_path(user.id) do %>
            <% if user.id == tweet.user_id%>
              <%if user.avatar.attached?%>
                <div class="user_flex">
                  <%= image_tag user.avatar, class: "avatar"%>
                </div>
              <%else%>
                <div class="user_flex">
                  <%= image_tag "icons_avatars/unknow_icon.png", class: "avatar"%>
                </div>
              <%end%>
              <%= tag.span user.name, class: "user_name" %>
              <span>@<%= tag.span  user.username%></span>
            <%end%>
          <% end %>
      <% end %>
      <%= link_to tweet do %>
        <div class="time_text text_black">
          <%= tag.span time_ago_in_words(tweet.created_at).gsub(/about /, '') %> ago
        </div>
        <div class="text_black">
          <%= tag.span tweet.body %>
        </div>
      <% end %>
      <% if user_signed_in? && ((tweet.user_id == current_user.id) || (current_user.present? && current_user.admin?)) %>
        <div>
          <%= button_to tweet, method: :delete, class: "icons_tweets delete_icon" do %>
            <%= image_tag 'Icon-delete.png' %>
          <% end %>
          <%= link_to edit_tweet_path(tweet), class: "icons_tweets edit_icon" do %>
            <%= image_tag 'Icon-edit.png' %>
          <% end %>
        </div>
      <% end %>
      <%= link_to tweet do %>
        <div class="icon_tweet_comment">
          <%= image_tag 'Icon-coments.png' %>
          <%= @tweets.where(replied_to_id: tweet.id).size %>  
        </div>
      <% end %>
      <% if user_signed_in?%>
        <% like = Like.find_by(tweet_id: tweet.id, user_id: current_user.id) %>
          <% if like%>
            <div class="icon_tweet_like">
              <%= button_to url_for(controller: 'likes', action: 'destroy', id: like.id, tweet_id: tweet.id), method: :delete, remote: true, class: "icons_tweets"  do%>
                <%= image_tag 'Icon-unlike.png' %>
              <% end %>
              <%= @likes.where(tweet_id: tweet.id).size %> 
            </div>
          <% else %>
            <div class="icon_tweet_like">
              <%= button_to url_for(controller: 'likes', action: 'create', tweet_id: tweet.id), method: :post, remote: true, class: "icons_tweets" do %>
                <%= image_tag 'Icon-like.png' %>
              <% end %>
              <%= @likes.where(tweet_id: tweet.id).size %> 
            </div>
          <% end %>
      <% else %>
        <div class="icon_tweet_like">
        <%= image_tag 'Icon-like.png' %>
        <%= @likes.where(tweet_id: tweet.id).size %> 
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<h2 class= "home_text">Tweet Detail</h2>

<div class="tweet_box">
      <% @user.each do |user| %>
          <%= link_to profile_path(user.id) do %>
            <% if user.id == @tweet.user_id%>
              <%if user.avatar.attached?%>
                <div class="user_flex">
                  <%= image_tag user.avatar, class: "avatar"%>
                </div>
              <%else%>
                <div >
                  <%= image_tag "icons_avatars/unknow_icon.png", class: "avatar"%>
                </div>
              <%end%>
              <%= tag.span user.name, class: "user_name" %>
              <span>@<%= tag.span  user.username%></span>
            <%end%>
          <% end %>
      <% end %>
      <%= link_to @tweet do %>
        <div class="time_text text_black">
          <%= tag.span time_ago_in_words(@tweet.created_at).gsub(/about /, '') %> ago
        </div>
        <div class="text_black">
          <%= tag.span @tweet.body %>
        </div>
      <% end %>
      <% if user_signed_in? && ((@tweet.user_id == current_user.id) || (current_user.present? && current_user.admin?)) %>
        <div>
          <%= button_to @tweet, method: :delete, class: "icons_tweets delete_icon" do %>
            <%= image_tag 'Icon-delete.png' %>
          <% end %>

          <%= link_to edit_tweet_path(@tweet), class: "icons_tweets edit_icon" do %>
            <%= image_tag 'Icon-edit.png' %>
          <% end %>
        </div>
      <% end %>
      <%= link_to @tweet do %>
        <div class="icon_tweet_comment">
          <%= image_tag 'Icon-coments.png' %>
          <%= @tweets.where(replied_to_id: @tweet.id).size %>  
        </div>
      <% end %>
      <% if user_signed_in?%>
        <% like = Like.find_by(tweet_id: @tweet.id, user_id: current_user.id) %>
          <% if like%>
            <div class="icon_tweet_like">
              <%= button_to url_for(controller: 'likes', action: 'destroy', id: like.id, tweet_id: @tweet.id), method: :delete, remote: true, class: "icons_tweets"  do%>
                <%= image_tag 'Icon-unlike.png' %>
              <% end %>
              <%= @likes.where(tweet_id: @tweet.id).size %> 
            </div>
          <% else %>
            <div class="icon_tweet_like">
              <%= button_to url_for(controller: 'likes', action: 'create', tweet_id: @tweet.id), method: :post, remote: true, class: "icons_tweets" do %>
                <%= image_tag 'Icon-like.png' %>
              <% end %>
              <%= @likes.where(tweet_id: @tweet.id).size %> 
            </div>
          <% end %>
      <% else %>
        <div class="icon_tweet_like">
        <%= image_tag 'Icon-like.png' %>
        <%= @likes.where(tweet_id: @tweet.id).size %> 
        </div>
      <% end %>
    </div>
</div>

<div class="line">
</div>

<% if user_signed_in?%>
  <div class="show_form">
    <%= render "form", tweet: @tweetnew, replied_to_id: @tweet.id %>
  </div>
<% end %>


<div id="replies">
<% @tweets.reverse().each do |tweet| %>
  <% if tweet.replied_to_id == @tweet.id%>
      <div class="tweet_box">
        <% @user.each do |user| %>
            <%= link_to profile_path(user.id) do %>
              <% if user.id == tweet.user_id%>
                <%if user.avatar.attached?%>
                  <div class="user_flex">
                    <%= image_tag user.avatar, class: "avatar"%>
                  </div>
                <%else%>
                  <div >
                    <%= image_tag "icons_avatars/unknow_icon.png", class: "avatar"%>
                  </div>
                <%end%>
                <%= tag.span user.name, class: "user_name" %>
                <span>@<%= tag.span  user.username%></span>
              <%end%>
            <% end %>
        <% end %>
        <%= link_to tweet do %>
          <div class="time_text text_black">
            <%= tag.span time_ago_in_words(tweet.created_at).gsub(/about /, '') %> ago
          </div>
          <div class="text_black">
            <%= tag.span tweet.body %>
          </div>
        <% end %>
        <% if user_signed_in? && ((tweet.user_id == current_user.id) || (current_user.present? && current_user.admin?)) %>
          <div>
            <%= button_to tweet, method: :delete, class: "icons_tweets delete_icon" do %>
              <%= image_tag 'Icon-delete.png' %>
            <% end %>
            <%= link_to edit_tweet_path(tweet), class: "icons_tweets edit_icon" do %>
              <%= image_tag 'Icon-edit.png' %>
            <% end %>
          </div>
        <% end %>
        <%= link_to tweet do %>
          <div class="icon_tweet_comment">
            <%= image_tag 'Icon-coments.png' %>
            <%= @tweets.where(replied_to_id: tweet.id).size %>  
          </div>
        <% end %>
        <% if user_signed_in?%>
          <% like = Like.find_by(tweet_id: tweet.id, user_id: current_user.id) %>
            <% if like%>
              <div class="icon_tweet_like">
                <%= button_to url_for(controller: 'likes', action: 'destroy', id: like.id, tweet_id: tweet.id), method: :delete, remote: true, class: "icons_tweets"  do%>
                  <%= image_tag 'Icon-unlike.png' %>
                <% end %>
                <%= @likes.where(tweet_id: tweet.id).size %> 
              </div>
            <% else %>
              <div class="icon_tweet_like">
                <%= button_to url_for(controller: 'likes', action: 'create', tweet_id: tweet.id), method: :post, remote: true, class: "icons_tweets" do %>
                  <%= image_tag 'Icon-like.png' %>
                <% end %>
                <%= @likes.where(tweet_id: tweet.id).size %> 
              </div>
            <% end %>
        <% else %>
          <div class="icon_tweet_like">
          <%= image_tag 'Icon-like.png' %>
          <%= @likes.where(tweet_id: tweet.id).size %> 
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= user.username %>
    <%if user.avatar.attached?%>
      <div >
        <%= image_tag user.avatar%>
      </div>
    <%else%>
      <div >
        <%= image_tag "icons_avatars/unknow_icon.png"%>
      </div>
    <%end%>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_registration_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<h2 class= "home_text"> Profile </h2>

<div id="users">
    <%if @user.avatar.attached?%>
      <div >
        <%= image_tag @user.avatar, class: "avatar_profile" %>
      </div>
    <%else%>
      <div >
        <%= image_tag "icons_avatars/unknow_icon.png", class: "avatar_profile" %>
      </div>
    <%end%>
    <%= tag.span @user.name, class: "user_name_profile" %>
    <span class="user_name_profile_tag">@<%= tag.span @user.username %></span>
    <span class="time_profile_text"> Joined on <%= @user.created_at.strftime("%B %d, %Y") %> </span>
</div>

<% if (!current_user.nil? && current_user.id == @user.id) || current_user.admin? %>
  <div class="edit_profile">
    <%= link_to "EDIT PROFILE", edit_user_registration_path, class: "button_edit_profile" %>
  </div>
<% end %>

<div class="tabs">
  <div class="tab">
    <input type="radio" id="tab-1" name="tab-group-1" checked>
        <label for="tab-1">Tweets(<%= Tweet.where(user_id: @user.id).count %>)</label>
        <div class="content">
          <% @tweets.reverse().each do |tweet| %>
            <% if tweet.user_id == @user.id%>
              <div class="tweet_box">
                <%= link_to profile_path(@user.id) do %>
                      <% if @user.id == tweet.user_id%>
                        <%if @user.avatar.attached?%>
                          <div class="user_flex">
                            <%= image_tag @user.avatar, class: "avatar"%>
                          </div>
                        <%else%>
                          <div >
                            <%= image_tag "icons_avatars/unknow_icon.png", class: "avatar"%>
                          </div>
                        <%end%>
                        <%= tag.span @user.name, class: "user_name" %>
                        <span>@<%= tag.span  @user.username%></span>
                      <%end%>
                <% end %>
                <%= link_to tweet do %>
                  <div class="time_text text_black">
                    <%= tag.span time_ago_in_words(tweet.created_at).gsub(/about /, '') %> ago
                  </div>
                  <div class="text_black">
                    <%= tag.span tweet.body %>
                  </div>
                <% end %>
                <% if user_signed_in? && ((tweet.user_id == current_user.id) || (current_user.present? && current_user.admin?)) %>
                  <div>
                    <%= button_to tweet, method: :delete, class: "icons_tweets delete_icon" do %>
                      <%= image_tag 'Icon-delete.png' %>
                    <% end %>

                    <%= link_to edit_tweet_path(tweet), class: "icons_tweets edit_icon" do %>
                      <%= image_tag 'Icon-edit.png' %>
                    <% end %>
                  </div>
                <% end %>
                <%= link_to tweet do %>
                  <div class="icon_tweet_comment">
                    <%= image_tag 'Icon-coments.png' %>
                    <%= @tweets.where(replied_to_id: tweet.id).size %>  
                  </div>
                <% end %>
                <% if user_signed_in?%>
                  <% like = Like.find_by(tweet_id: tweet.id, user_id: current_user.id) %>
                    <% if like%>
                      <div class="icon_tweet_like">
                        <%= button_to url_for(controller: 'likes', action: 'destroy', id: like.id, tweet_id: tweet.id), method: :delete, remote: true, class: "icons_tweets"  do%>
                          <%= image_tag 'Icon-unlike.png' %>
                        <% end %>
                        <%= @likes.where(tweet_id: tweet.id).size %> 
                      </div>
                    <% else %>
                      <div class="icon_tweet_like">
                        <%= button_to url_for(controller: 'likes', action: 'create', tweet_id: tweet.id), method: :post, remote: true, class: "icons_tweets" do %>
                          <%= image_tag 'Icon-like.png' %>
                        <% end %>
                        <%= @likes.where(tweet_id: tweet.id).size %> 
                      </div>
                    <% end %>
                <% else %>
                  <div class="icon_tweet_like">
                    <%= image_tag 'Icon-like.png' %>
                    <%= @likes.where(tweet_id: tweet.id).size %> 
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
    <div class="tab">
    <input type="radio" id="tab-2" name="tab-group-1">
    <label for="tab-2"><% likes = Like.where(user_id: @user.id) %> Likes(<%= likes.count%>)</label>
    <div class="content">
      <% likes.reverse().each do |like| %>
        <% likeTweets = Tweet.where(id: like.tweet_id)%>
          <% likeTweets.each do |likeTweet| %>
            <% user = User.where(id: likeTweet.user_id)%>
              <div class="tweet_box">
                <% user.each do |users|%>
                  <div>
                  <%if users.avatar.attached?%>
                    <div class="user_flex">
                      <%= image_tag users.avatar, class: "avatar" %>
                    </div>
                  <%else%>
                    <div class="user_flex">
                      <%= image_tag "icons_avatars/unknow_icon.png", class: "avatar" %>
                    </div>
                  <%end%>
                  <%= tag.span users.name, class: "user_name" %>
                  <span>@<%= tag.span  users.username%></span>
                  <% if likeTweet.created_at == likeTweet.updated_at%>
                    <div class="time_text text_black">
                      <%= tag.span time_ago_in_words(likeTweet.created_at).gsub(/about /, '') %> ago
                    </div>
                  <% else %>
                    <div class="time_text text_black">
                      Edited <%= tag.span time_ago_in_words(likeTweet.created_at).gsub(/about /, '') %> ago
                    </div>
                  <% end %>
                  <div class="text_black">
                    <%= tag.span likeTweet.body %>
                  </div>
                  <% if user_signed_in? && ((likeTweet.user_id == current_user.id) || (current_user.present? && current_user.admin?)) %>
                    <div>
                      <%= button_to likeTweet, method: :delete, class: "icons_tweets delete_icon" do %>
                        <%= image_tag 'Icon-delete.png' %>
                      <% end %>
                      <%= link_to edit_tweet_path(likeTweet), class: "icons_tweets edit_icon" do %>
                        <%= image_tag 'Icon-edit.png' %>
                      <% end %>
                    </div>
                  <% end %>
                  <%= link_to likeTweet do %>
                    <div class="icon_tweet_comment">
                      <%= image_tag 'Icon-coments.png' %>
                      <%= @tweets.where(replied_to_id: likeTweet.id).size %>  
                    </div>
                  <% end %>
                  <% if user_signed_in?%>
                    <% like = Like.find_by(tweet_id: likeTweet.id, user_id: current_user.id) %>
                      <% if like%>
                        <div class="icon_tweet_like">
                          <%= button_to url_for(controller: 'likes', action: 'destroy', id: like.id, tweet_id: likeTweet.id), method: :delete, remote: true, class: "icons_tweets"  do%>
                            <%= image_tag 'Icon-unlike.png' %>
                          <% end %>
                          <%= @likes.where(tweet_id: likeTweet.id).size %> 
                        </div>
                      <% else %>
                        <div class="icon_tweet_like">
                          <%= button_to url_for(controller: 'likes', action: 'create', tweet_id: likeTweet.id), method: :post, remote: true, class: "icons_tweets" do %>
                            <%= image_tag 'Icon-like.png' %>
                          <% end %>
                          <%= @likes.where(tweet_id: likeTweet.id).size %> 
                        </div>
                      <% end %>
                  <% else %>
                    <div class="icon_tweet_like">
                    <%= image_tag 'Icon-like.png' %>
                    <%= @likes.where(tweet_id: tweet.id).size %> 
                    </div>
                  <% end %>
                  </div>
                <% end %>
              </div>
          <% end %>
      <%end %>
    </div>
  </div>
</div>